exclude: 'docks|Dockerfile|.git|'
default_stages: [pre-commit]
fail_fast: false

repos:
- repo: local
  hooks:
  - id: ruff
    name: Запуск ruff с --fix
    entry: ruff check --fix
    language: system
    files: \.py$
  - id: ruff-format
    name: Запуск ruff-format
    entry: ruff format
    language: system
    files: \.py$